// bootstrap.js
//
// Main bootstrap file for the gfx_host extension
// Exports all graphics and input ops to JavaScript

import {
  op_gfx_get_preferred_surface_format,
  op_gfx_surface_configure,
  op_gfx_device_create_shader,
  op_gfx_device_create_buffer_init,
  op_gfx_device_create_buffer,
  op_gfx_queue_write_buffer,
  op_gfx_clear_buffer,
  op_gfx_device_create_texture,
  op_gfx_texture_create_view,
  op_gfx_device_create_sampler,
  op_gfx_device_create_bind_group_layout,
  op_gfx_device_create_pipeline_layout,
  op_gfx_device_create_bind_group,
  op_gfx_device_create_pipeline,
  op_gfx_surface_draw,
  op_gfx_write_texture_image,
  op_gfx_pipeline_get_bind_group_layout,
  op_gfx_render_to_texture,
  op_gfx_copy_texture_to_texture,
  op_gfx_copy_buffer_to_texture,
  op_gfx_decode_image_store,
  op_gfx_upload_decoded_image_to_texture,
  op_gfx_decoded_image_drop,
  op_gfx_decoded_image_stats,
  op_gfx_decoded_image_stats_detailed,
  op_gfx_resource_stats,
  op_gfx_resize_decoded_image,
  op_gfx_render_depth_only,
  op_gfx_resource_drop,
  op_gfx_texture_drop,
  op_gfx_buffer_drop,
  op_gfx_bind_group_drop,
  op_gfx_flush_commands,
  op_gfx_render_xr_frame,
  op_gfx_multi_draw_indexed_indirect,
  op_gfx_queue_submit_empty,

  // Compute shader ops
  op_gfx_device_create_compute_pipeline,
  op_gfx_compute_pipeline_get_bind_group_layout,
  op_gfx_compute_dispatch,
  op_gfx_compute_dispatch_indirect,
  op_gfx_compute_batch,

  // GPUTimer / Timestamp query ops
  op_gfx_device_create_query_set,
  op_gfx_query_set_destroy,
  op_gfx_has_timestamp_query,
  op_gfx_get_timestamp_period,
  op_gfx_timestamp_batch,
  op_gfx_buffer_map_async,
  op_gfx_buffer_map_poll,
  op_gfx_buffer_map_wait,
  op_gfx_buffer_map_finish,
  op_gfx_buffer_get_mapped_range,
  op_gfx_buffer_unmap,
  op_gfx_write_timestamp,
  op_gfx_has_feature,

  // Input ops
  op_input_poll_events,
  op_input_get_window_size,
  op_input_request_pointer_lock,
  op_input_exit_pointer_lock,
  op_input_is_pointer_locked,
  op_input_set_cursor_style,

  // Indexed DB
  op_indexeddb_open,
  op_indexeddb_get,
  op_indexeddb_put,
  op_indexeddb_delete,
  op_indexeddb_get_all_keys,
  op_indexeddb_clear,
  op_indexeddb_store_exists,

  // XR
  op_xr_is_supported,
  op_xr_request_session,
  op_xr_wait_frame,
  op_xr_get_viewer_pose,
  op_xr_acquire_swapchain_image,
  op_xr_release_swapchain_image,
  op_xr_end_frame,
  op_xr_end_session,
  op_xr_poll_events,
  op_xr_get_swapchain_texture_view,
  op_xr_get_input_sources,
  op_xr_frame_begin,
  op_xr_frame_wait_start,
  op_xr_frame_wait_poll,
  op_xr_frame_wait_finish,
  op_xr_set_clip_planes,
  op_xr_haptic_pulse,
  op_xr_haptic_stop,

  // Audio ops
  op_audio_create_context,
  op_audio_context_current_time,
  op_audio_context_close,
  op_audio_create_gain,
  op_audio_create_buffer_source,
  op_audio_create_oscillator,
  op_audio_create_panner,
  op_audio_create_biquad_filter,
  op_audio_create_stereo_panner,
  op_audio_create_delay,
  op_audio_create_dynamics_compressor,
  op_audio_create_analyser,
  op_audio_connect,
  op_audio_disconnect,
  op_audio_param_set_value,
  op_audio_param_set_value_at_time,
  op_audio_param_set_target_at_time,
  op_audio_param_linear_ramp,
  op_audio_param_exponential_ramp,
  op_audio_decode_audio_data,
  op_audio_buffer_drop,
  op_audio_buffer_source_set_buffer,
  op_audio_buffer_source_start,
  op_audio_buffer_source_stop,
  op_audio_buffer_source_set_loop,
  op_audio_buffer_source_set_loop_start,
  op_audio_buffer_source_set_loop_end,
  op_audio_oscillator_set_type,
  op_audio_oscillator_start,
  op_audio_oscillator_stop,
  op_audio_panner_configure,
  op_audio_biquad_set_type,
  op_audio_listener_set_position,
  op_audio_listener_set_orientation,
  op_audio_node_drop,

  // event loop
  op_yield_to_runtime,
  op_http_fetch,
} from "ext:core/ops";

globalThis.__yieldToRuntime = op_yield_to_runtime;
globalThis.__httpFetch = op_http_fetch;

globalThis.__xr = {
  op_xr_is_supported,
  op_xr_request_session,
  op_xr_wait_frame,
  op_xr_get_viewer_pose,
  op_xr_acquire_swapchain_image,
  op_xr_release_swapchain_image,
  op_xr_end_frame,
  op_xr_end_session,
  op_xr_poll_events,
  op_xr_get_swapchain_texture_view,
  op_xr_get_input_sources,
  op_xr_frame_begin,
  op_xr_frame_wait_start,
  op_xr_frame_wait_poll,
  op_xr_frame_wait_finish,
  op_xr_set_clip_planes,
  op_xr_haptic_pulse,
  op_xr_haptic_stop,
};

globalThis.__indexeddb = {
  op_indexeddb_open,
  op_indexeddb_get,
  op_indexeddb_put,
  op_indexeddb_delete,
  op_indexeddb_get_all_keys,
  op_indexeddb_clear,
  op_indexeddb_store_exists,
};

// Expose graphics ops to globalThis
globalThis.__gfx = {
  op_gfx_get_preferred_surface_format,
  op_gfx_surface_configure,
  op_gfx_device_create_shader,
  op_gfx_device_create_buffer_init,
  op_gfx_device_create_buffer,
  op_gfx_queue_write_buffer,
  op_gfx_clear_buffer,
  op_gfx_device_create_texture,
  op_gfx_texture_create_view,
  op_gfx_device_create_sampler,
  op_gfx_device_create_bind_group_layout,
  op_gfx_device_create_pipeline_layout,
  op_gfx_device_create_bind_group,
  op_gfx_device_create_pipeline,
  op_gfx_surface_draw,
  op_gfx_write_texture_image,
  op_gfx_pipeline_get_bind_group_layout,
  op_gfx_render_to_texture,
  op_gfx_copy_texture_to_texture,
  op_gfx_copy_buffer_to_texture,
  op_gfx_decode_image_store,
  op_gfx_upload_decoded_image_to_texture,
  op_gfx_decoded_image_drop,
  op_gfx_decoded_image_stats,
  op_gfx_decoded_image_stats_detailed,
  op_gfx_resource_stats,
  op_gfx_resize_decoded_image,
  op_gfx_render_depth_only,
  op_gfx_resource_drop,
  op_gfx_texture_drop,
  op_gfx_buffer_drop,
  op_gfx_bind_group_drop,
  op_gfx_flush_commands,
  op_gfx_render_xr_frame,
  op_gfx_multi_draw_indexed_indirect,
  op_gfx_queue_submit_empty,

  // Compute shader ops
  op_gfx_device_create_compute_pipeline,
  op_gfx_compute_pipeline_get_bind_group_layout,
  op_gfx_compute_dispatch,
  op_gfx_compute_dispatch_indirect,
  op_gfx_compute_batch,

  // GPUTimer / Timestamp query ops
  op_gfx_device_create_query_set,
  op_gfx_query_set_destroy,
  op_gfx_has_timestamp_query,
  op_gfx_get_timestamp_period,
  op_gfx_timestamp_batch,
  op_gfx_buffer_map_async,
  op_gfx_buffer_map_poll,
  op_gfx_buffer_map_wait,
  op_gfx_buffer_map_finish,
  op_gfx_buffer_get_mapped_range,
  op_gfx_buffer_unmap,
  op_gfx_write_timestamp,
  op_gfx_has_feature,
};

// Expose audio ops to globalThis
globalThis.__audio = {
  op_audio_create_context,
  op_audio_context_current_time,
  op_audio_context_close,
  op_audio_create_gain,
  op_audio_create_buffer_source,
  op_audio_create_oscillator,
  op_audio_create_panner,
  op_audio_create_biquad_filter,
  op_audio_create_stereo_panner,
  op_audio_create_delay,
  op_audio_create_dynamics_compressor,
  op_audio_create_analyser,
  op_audio_connect,
  op_audio_disconnect,
  op_audio_param_set_value,
  op_audio_param_set_value_at_time,
  op_audio_param_set_target_at_time,
  op_audio_param_linear_ramp,
  op_audio_param_exponential_ramp,
  op_audio_decode_audio_data,
  op_audio_buffer_drop,
  op_audio_buffer_source_set_buffer,
  op_audio_buffer_source_start,
  op_audio_buffer_source_stop,
  op_audio_buffer_source_set_loop,
  op_audio_buffer_source_set_loop_start,
  op_audio_buffer_source_set_loop_end,
  op_audio_oscillator_set_type,
  op_audio_oscillator_start,
  op_audio_oscillator_stop,
  op_audio_panner_configure,
  op_audio_biquad_set_type,
  op_audio_listener_set_position,
  op_audio_listener_set_orientation,
  op_audio_node_drop,
};

// Expose input ops to globalThis
globalThis.__input = {
  op_input_poll_events,
  op_input_get_window_size,
  op_input_request_pointer_lock,
  op_input_exit_pointer_lock,
  op_input_is_pointer_locked,
  op_input_set_cursor_style,
};
